### ISSUE TITLE
Inconsistency in TAC Cases Query

### ISSUE THREAD

**Issue by pbrane** [pbrane/tac-case-api-service-monolith#25]
Jun reported:
Inconsistent output with design 

![Image](https://github.com/user-attachments/assets/415faa0f-c96a-486e-8ee0-fa67bad3b7f2)

Response can't indicate which key infor are missing.

**Comment by pbrane** [comment]
I cannot reproduce this problem.

**Comment by elu01** [comment]
This is invalidated. Jun Feng should quote the email field.
