### ISSUE TITLE
"caseCreatedDate" should be automatically generated when ticket created

### ISSUE THREAD

**Issue by chenjaixnin** [pbrane/tac-case-api-service-monolith#27]
after new ticket created, "caseCreatedDate" is null,I think "caseCreatedDate" should be automatically generated when ticket created
<img width="380" alt="Image" src="https://github.com/user-attachments/assets/685a53e5-13f4-49cd-9ccb-1a2e32f63952" />

**Comment by pbrane** [comment]
Fixed in commit:
https://github.com/pbrane/tac-case-api-service-monolith/commit/865f7e3f613ae1d17e8a81df9cc66d869b63dc64

You can test with docker or wait until I redeploy version 0.1.14 this afternoon.
