### ISSUE TITLE
When create a tacCase note, but JSON body 'text' only support 255 characters. It is so short

### ISSUE THREAD

**Issue by JunfengKe** [pbrane/tac-case-api-service-monolith#28]
When create a tacCase note, but JSON body 'text' only support 255 characters. It is so short.
![Image](https://github.com/user-attachments/assets/9f65be3d-62ca-4e9c-b564-1a93a71c2df8)

**Comment by pbrane** [comment]
Increased to 64k. This is a configuration that only effects the built in H2 DB.
https://github.com/pbrane/tac-case-api-service-monolith/commit/68e8ba2081810ee4e2adf788e0debcf7a520f48a
