### ISSUE TITLE
Create RMA problem description only support 255 characters

### ISSUE THREAD

**Issue by JunfengKe** [pbrane/tac-case-api-service-monolith#29]
Create RMA problem description only support 255 characters![Image](https://github.com/user-attachments/assets/9f1c7572-e301-4666-9058-26e5df8a4178)

**Comment by pbrane** [comment]
Spring Boot RestController default limit of 1MB made configurable and set to 20MB as a default.
https://github.com/pbrane/tac-case-api-service-monolith/commit/5a9890aace41fe7b2ce4d5f4acd33ee61834ab92
