### ISSUE TITLE
Upload a attachments to a TAC case and file size greater  than 2M, not successfully

### ISSUE THREAD

**Issue by JunfengKe** [pbrane/tac-case-api-service-monolith#30]
Upload a attachments to a TAC case and file size greater  than 2M, not successfully
Team group include the detail picture

**Comment by pbrane** [comment]
Fixed. Added new varible to change Spring Boot Multipart file defaults: API_SVR_MAX_FILE_SIZE_MB with a default of 20MB

RestControllerConfig.java:
...
    @Value("${API_SVR_MAX_FILE_SIZE_MB:20}")
    private Integer maxFileSize;


https://github.com/pbrane/tac-case-api-service-monolith/commit/5a9890aace41fe7b2ce4d5f4acd33ee61834ab92
